service: sessions-service
frameworkVersion: ">=3.22.0"

provider:
  name: aws
  runtime: provided.al2
  stage: dev
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-2'}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        - Fn::GetAtt: [candidatesTable, Arn]

package:
  exclude:
    - .deno_dir/gen/file
    - node_modules
    - package-lock.json

functions:
  getSessions:
    handler: src/api/sessions.get
    layers:
      - !GetAtt Deno.Outputs.LayerArn
    memorySize: 128
    description: Get session by id
    events:
      - http:
          path: sessions/{id}
          method: get

resources:
  Transform: AWS::Serverless-2016-10-31
  Resources:
    Deno:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:us-east-1:390065572566:applications/deno
          SemanticVersion: 1.25.2

    candidatesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sessions
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-scriptable-plugin
  - serverless-offline

custom:
  scriptHooks:
    before:package:createDeploymentArtifacts: bash ./scripts/serverless/before-package-createDeploymentArtifacts.sh
  serverless-offline:
    useDocker: true
